### ISSUE TITLE
Vertices with no edges

### ISSUE THREAD

**Issue by terrykong** [r2d4/virgo#6]
Hi,

Very cool package. I was wondering if it's possible to support the following graph:
```
a -> b
c
d
```
where the vertices may have no edges. In terms of a DAG, this would help me define things where `c` and `d` have no parents so they can be run in parallel.

I guess an even simpler case is supporting a single vertex as a graph
```
a
```
I could create a cycle, but then I can't do a topological sort.

Thanks!

**Comment by r2d4** [comment]
Added it to the grammar in #7 - should be able to do `a` or `a,b,c` to define a vertex or multiple vertices. Opened #8 to clean up a bunch of the Go topological sort and make it more usable for that purpose. I have the code written, just need to clean it up and make it open source-able
